### ISSUE TITLE
Retry weekday

### ISSUE THREAD

**Issue by thevery** [CSC-MobDev-2016/colloquium1#8]
Available options are 10.05 - 13.05, approximate time slot is 16:00 - 19:00

**Comment by thevery** [comment]
10.05.16 - Tuesday

**Comment by thevery** [comment]
11.05.16 - Wednesday

**Comment by thevery** [comment]
12.05.16 - Thursday

**Comment by thevery** [comment]
13.05.16 - Friday

**Comment by thevery** [comment]
You can downvote certain days, too!

**Comment by AnastasiaSulyagina** [comment]
Можно так и оставить, отличное распределение :)

**Comment by thevery** [comment]
11.05.16 - Wednesday
